package com.enfotrix.cricscore.models



data class PlayerModel(
    var pID: Int  = 0,
    var fireBasePId: String = "",
    var playerProfileId: String = "",
    var teamID: String = "",
    val matches: String = "",
    val firstName: String = "",
    val lastName: String = "",
    var wicketType: String = "",
    var isOut: Boolean = false,
    val country: String = "",
    val city: String = "",
    val dob: String = "",
    val playingRole: String = "",
    val jerseyNumber: String = "",
    val height: String = "",
    val weight: String = "",
    val nickName: String = "",
    val maritalStatus: String = "",
    val contactNumber: String = "",
    val currentClub: String = "",
    val awards: String = "",
    val preferredFormat: String = "",
    val languages: String = "",
    val teamRepresenting: String = "",
    val tTen: String = "",
    val tTwenty: String = "",
    val odi: String = "",
    val others: String = "",
    val clubDs: String = "",
    val tournaments: String = "",
    var isWicketkeeper: Boolean = false,
    val wicketkeeperDetails: String = "",
    val captainDetails: String = "",
    var captainRole: String = "",
    var isCaptain: Boolean = false,
    var isViceCaptain: Boolean = false,
    var team: String = "",
    var matchRole: String = ""
)
